In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# import sys
# print(sys.executable)

In [4]:
df = pd.read_csv("data/NSE_data_all_stocks_2016.csv")

In [5]:
df.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
0,04-Jan-16,EGAD,Eaagads Ltd,8.2,14,25,25,25,26.75,-1.75,6.54%,400,-
1,04-Jan-16,KUKZ,Kakuzi Plc,300,423.5,317,348,332,317,15,4.73%,200,-
2,04-Jan-16,KAPC,Kapchorua Tea Kenya Plc,59,95,200,200,200,200,-,-,800,100
3,04-Jan-16,LIMT,Limuru Tea Plc,385,475,"1,085.00","1,085.00","1,085.00","1,085.00",-,-,-,-
4,04-Jan-16,SASN,Sasini Plc,14.8,19.6,19.5,19.5,19.5,19.55,-0.05,0.26%,700,-

In [8]:
len(df)

16800

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16800 entries, 0 to 16799
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       16800 non-null  str
 1   CODE       16800 non-null  str
 2   NAME       16800 non-null  str
 3   12m Low    16800 non-null  str
 4   12m High   16800 non-null  str
 5   Day Low    16800 non-null  str
 6   Day High   16800 non-null  str
 7   Day Price  16800 non-null  str
 8   Previous   16800 non-null  str
 9   Change     16800 non-null  str
 10  Change%    16800 non-null  str
 11  Volume     16800 non-null  str
 12  Adjust     16800 non-null  str
dtypes: str(13)
memory usage: 1.7 MB

In [12]:
df.describe()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
count,16800,16800,16800,16800,16800,16800,16800,16800,16800,16800,16800,16800,16800
unique,248,69,69,99,104,1979,1975,2411,2412,885,863,3810,782
top,02-Aug-16,EGAD,Eaagads Ltd,2,55.5,5.5,5.5,5.5,5.5,-,-,-,-
freq,69,248,248,484,496,487,503,475,476,5961,5966,4373,14355

In [14]:
df.shape

(16800, 13)

In [15]:
df.nunique()

DATE          248
CODE           69
NAME           69
12m Low        99
12m High      104
Day Low      1979
Day High     1975
Day Price    2411
Previous     2412
Change        885
Change%       863
Volume       3810
Adjust        782
dtype: int64

In [21]:
df.isnull().any()

DATE         False
CODE         False
NAME         False
12m Low      False
12m High     False
Day Low      False
Day High     False
Day Price    False
Previous     False
Change       False
Change%      False
Volume       False
Adjust       False
dtype: bool

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [6]:
df.columns

Index(['date', 'code', 'name', '12m_low', '12m_high', 'day_low', 'day_high',
       'day_price', 'previous', 'change', 'change%', 'volume', 'adjust'],
      dtype='str')

In [7]:
from datetime import datetime

In [8]:
df['date']= pd.to_datetime(df['date'],format='%d-%b-%y')

In [9]:
df.dtypes

date         datetime64[us]
code                    str
name                    str
12m_low                 str
12m_high                str
day_low                 str
day_high                str
day_price               str
previous                str
change                  str
change%                 str
volume                  str
adjust                  str
dtype: object

In [12]:
print(df['date'])

0       2016-01-04
1       2016-01-04
2       2016-01-04
3       2016-01-04
4       2016-01-04
           ...
16795   2016-12-30
16796   2016-12-30
16797   2016-12-30
16798   2016-12-30
16799   2016-12-30
Name: date, Length: 16800, dtype: datetime64[us]